### PR TITLE
Add IDL defs for Report and ReportBodys

### LINKED ISSUE #44: OOM reporting in "crash" report
Currently developers have little insight into implication of their memory footprint, in particular it would be great to consider exposing OOM as the reason for crashes (and potentially other coarse grain signals)
Is this inherently not possible via reporting API due to security reasons?
The explainer says that [crash report won't indicate any detail except unique ID due to security](https://github.com/WICG/reporting/blob/master/EXPLAINER.md#crashes)

### PR DESCRIPTION
**Pull request by patrickkettner**
@RByers 

fixes #44

### CODE REVIEW

**Comment by igrigorik** [comment]
@patrickkettner @RByers @dcreager should `DeprecationReportBody` / `CrashReportBody` live in this spec? To the extent possible, I'd prefer if we focus this spec on the reporting framework and plumbing, and defer definitions of reports to upstream specs.

**Comment by RByers** [comment]
I'd like to keep the overhead low, but I don't see a problem with creating a second spec in this repro specific to deprecation, intervention and crash reports if you think the modularity would be valuable.

**Comment by patrickkettner** [comment]
fine with me. ill update the pr to be a separate list

**Comment by dcreager** [comment]
I think this was superseded by #87 and #92

**Pull request closed without merging**
