### PR TITLE
Define the MIME type in more detail.

### PR DESCRIPTION
**Pull request by mikewest**
@mnot: I'm cargo-culting from other specs for most of this. WDYT?

+@annevk, @igrigorik, @patrickkettner: FYI.

This aims to close https://github.com/WICG/reporting/issues/51.

### CODE REVIEW

**Comment by mikewest** [comment]
> You're being inconsistent on report+json vs reports+json.

Good eye. I think it's all pluralized now.

**Comment by mikewest** [comment]
(Pluralized because the browser ought to be coalescing a set of reports into a bundle when possible to deliver to the server.)

**Comment by mnot** [comment]
Looks like it's in the ballpark. Send it to the media-types list for review.

**Comment by igrigorik** [comment]
@mnot @mikewest any updates on this front?

**Comment by mnot** [comment]
Did it get sent to the list?

**Comment by dcreager** [comment]
ping @mikewest, did you register the MIME type?  If not, I can do so

**Comment by dcreager** [comment]
Submitted a registration request for `application/reports+json` to IANA

**Comment by dcreager** [comment]
`application/reports+json` has been registered in the [provisional registry](https://www.iana.org/assignments/provisional-standard-media-types/provisional-standard-media-types.xhtml)

**Pull request merged**
